version: '3'
services:
  main_database:
    container_name: main-db
    image: postgres:11.19-alpine
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  app:
    container_name: main-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - main_database
    env_file:
      - .env.docker-dev
      - .env
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    command: ['yarn', 'dev']

volumes:
  postgres:
