FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY .gitmodules .gitmodules
COPY .git .git

RUN git submodule update --init --recursive

COPY package.json .
COPY src/modules/mail/templates/package.json .

RUN yarn --exact --ignore-scripts

COPY . .
