### Variables 
# @apiurl = http://localhost:3000
@apiurl = https://loryblu-homologation.onrender.com

### POST /auth/register
POST {{apiurl}}/auth/register HTTP/1.1
Content-Type: application/json
{
  "email": "email@example.com",
  "password": "stringW#3",
  "policiesAccepted": true,
  "parentName": "John Doe",
  "childrenName": "John Jr Doe",
  "childrenBirthDate": "2009-02-28",
  "childrenGender": "male"
}

### POST /login/register
POST {{apiurl}}/login/register HTTP/1.1
Content-Type: application/json
{
  "email": "email@example.com",
  "password": "stringW#3",
}

### GET /task
GET {{apiurl}}/task HTTP/1.1

### POST /task
POST {{apiurl}}/task HTTP/1.1
Content-Type: application/json
{
  "childrenId": 1,
  "categoryId": "44f29121-b7b1-4d1a-bbff-5f1cf2fc5497",
  "shift": "morning",
  "frequency": [
    "mon"
  ],
  "order": 0
}

### PATCH /task
PATCH {{apiurl}}/task HTTP/1.1
Content-Type: application/json
{
  "childrenId": 1,
  "categoryId": "44f29121-b7b1-4d1a-bbff-5f1cf2fc5497",
  "shift": "morning",
  "frequency": [
    "mon"
  ],
  "order": 0
}


### POST /auth/recovery
POST {{apiurl}}/login/register HTTP/1.1
Content-Type: application/json
{
  "email": "email@example.com"
}

### PUT /auth/recovery
PUT {{apiurl}}/auth/set-password HTTP/1.1
Content-Type: application/json
{
  "password": "stringW#3",
  "recoveryToken": "string"
}

