### Variables 
@apiurl = http://localhost:5500
# @apiurl = https://loryblu-homologation.onrender.com
@authToken = {{login.response.body.data.accessToken}}


### POST /auth/recovery
POST {{apiurl}}/login/register HTTP/1.1
Content-Type: application/json

{
  "email": "email@example.com"
}

### PUT /auth/recovery
PUT {{apiurl}}/auth/set-password HTTP/1.1
Content-Type: application/json

{
  "password": "stringW#3",
  "recoveryToken": "string"
}

### POST /auth/register
POST {{apiurl}}/auth/register
Content-Type: application/json

{
  "email": "kauane7@email.com",
  "password": "stringW#3",
  "policiesAccepted": true,
  "parentName": "Kauane Santos",
  "childrenName": "John Santos",
  "childrenBirthDate": "2009-02-28",
  "childrenGender": "male"
}

### Get /auth/account
GET {{apiurl}}/auth/account
Authorization: Bearer {{authToken}}

### POST auth/login
# @name login
POST {{apiurl}}/auth/login 
Content-Type: application/json

{
  "email": "kauane7@email.com",
  "password": "stringW#3"
}

### POST /auth/logout
# @name logout
POST {{apiurl}}/auth/logout
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaWQiOiI2NTgyMDFiNy1lZWEyLTQzNjktYjQyOC1kM2EzZTVmZTlkYTkiLCJwaWQiOiI3NjczZTdkYi1jNjNkLTQ0MGUtYmI0YS0zNjhjMWI0MGRiYTUiLCJpYXQiOjE3Mjk2MTI3ODgsImV4cCI6MTcyOTYxNjM4OCwic3ViIjoiYWNjZXNzIn0.9lo7Hmhh6GKO4U4QWuF4S_Tu0NaiHO8t0_QTScWcpQ8"

}
### POST /task
POST {{apiurl}}/task 
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "childrenId": 1,
  "categoryId": "44f29121-b7b1-4d1a-bbff-5f1cf2fc5497",
  "shift": "morning",
  "frequency": [
   "sat"
  ],
  "order": 0
}

### GET /task?childrenId=2&frequency=mon
GET {{apiurl}}/task?childrenId=4&frequency=sat
Authorization: Bearer {{authToken}}

### Delete /task/id
DELETE {{apiurl}}/task?childrenId=3&taskId=10
Authorization: Bearer {{authToken}}


### PATCH /task
PATCH {{apiurl}}/task?childrenId=1&taskId=91
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "childrenId": 1,
  "categoryId": "44f29121-b7b1-4d1a-bbff-5f1cf2fc5497",
  "shift": "afternoon",
  "frequency": [
    "tue"
  ],
  "order": 0
}



