name: Run tests

on:
  pull_request:
    branches:
      - develop
      - homologation

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn

      - name: Unit tests
        run: yarn test
